[lint]

ignore = [
    "F601", # Duplicate literal
    "N999", # Invalid module name
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25