blank_issues_enabled: false
contact_links:
  - name: API Repository
    url: https://github.com/Pirate-Weather/pirateweather/
    about: Report issues with and request features to the API here.
  - name: Home Assistant Repository
    url: https://github.com/alexander0042/pirate-weather-ha
    about: Please report any issues with the Home Assistant integration here.