name: General Issue
description: Report an issue with the translations not covered by the other templates.
labels: ["Needs Review"]
body:

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
      placeholder: |
        Example:
          "The text is translated as..."
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Which language do you see the issue with?
      options: 
        - Arabic
        - Azerbaijani
        - Belarusian
        - Bulgarian
        - Bengali
        - Bosnian
        - Catalan
        - Czech
        - Danish
        - German
        - Greek
        - English
        - Esperanto
        - Spanish
        - Estonian
        - Finnish
        - French
        - Hebrew
        - Hindi
        - Croatian
        - Hungarian
        - Indonesian
        - Icelandic
        - Italian
        - Japanese
        - Georgian
        - Kannada
        - Korean
        - Cornish
        - Latvian
        - Malayam
        - Marathi
        - Norwegian Bokmål
        - Dutch
        - Punjabi
        - Polish
        - Portuguese
        - Romanian
        - Russian
        - Slovak
        - Slovenian
        - Serbian
        - Swedish
        - Tamil
        - Telugu
        - Tetum
        - Turkish
        - Ukrainian
        - Urdu
        - Igpay Atinlay
        - Simplified Chinese
        - Traditional Chinese
    validations:
      required: true

  - type: dropdown
    id: submit-pr
    attributes:
      label: Are you willing to submit a pull request to fix the issue?
      options: 
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowlegdements
      description: Before submitting an issue please read the steps below carefully.
      options:
        - label: I have searched this repository to see if the issue has already been reported.
          required: true
        - label: I have filled in the template to the best of my ability.
          required: true
        - label: I have written an informative title.
          required: true