name: "Lint"

on:
  push:
  pull_request:
  
permissions:
  contents: write

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

      - name: "Set up Python"
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.x"

      - name: "Install requirements"
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: "Format"
        run: ruff format .
          
      - name: "Check"
        run: ruff check --output-format=github . --fix
          
      - name: "Auto Commit"
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'style fixes by ruff'